# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#target 'ExampleSwiftUI' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#
#  # Pods for ExampleSwiftUI
#
#end

platform :ios, '12.3'
ENV['SWIFT_VERSION'] = '5.0'
use_frameworks!

workspace 'MeshulamWorkspace'

def shared_pods
  pod 'Alamofire'
  pod 'lottie-ios'
end


target 'ExampleSwiftUI' do
  pod 'MeshulamSDK'
end

##bitcode enable
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.3'
      
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      
      config.build_settings['LD_NO_PIE'] = 'NO'
    end
  end
end

