# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'MeshulamSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
#  pod 'lottie-ios'

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
#      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      config.build_settings['BUILD_LIBRARIES_FOR_DISTRIBUTION'] = 'YES'
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
  end
  # Pods for MeshulamSDK

end


