# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'objcTester' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'MeshulamSDK', :path => '../MeshulamSDK.podspec'
pod 'MeshulamSDK' , '~> 0.2.1'


  # Pods for objcTester

end
#
