# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'




target 'objcTester' do
  shared_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MeshulamSDK', :path => '../MeshulamSDK.podspec'
#pod 'MeshulamSDK'


post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
end
end
end



end
#
